version: "3.9"
services:
  postgres-warehouse:
    image: postgres:10.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
        # copy the sql script to create tables
      - ./DDL/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 5
  run:
    environment:
      - postgres_host=postgres-warehouse
      - postgres_database=postgres
      - postgres_user=postgres
      - postgres_password=postgres
    image: "dbt-example"
    depends_on:
      postgres-warehouse:
        condition: service_healthy
    volumes:
      - .:/app
    command: dbt --profiles-dir ./.dbt run